### ISSUE TITLE
Images after the first are not converted

### ISSUE THREAD

**Issue by acca** [alvaroreig/pocket2kindle#1]
First of all congratulation because this app makes a good work and it is very simple to install.

Unfortunately it does not convert correctly the images of my articles: only the first image is converted then other images are not present on the mobi version.

I'm available to give you more info about this behaviour if you need.

**Comment by alvaroreig** [comment]
Hi @acca,

You are right, in every article only the first image is displayed.

However, the conversion to mobi is not done by this software, I use Pocket-Plus-Calibre-Plugin ( https://github.com/mmagnus/Pocket-Plus-Calibre-Plugin). You can open the issue there, if the author fixes it I will update the software to use the new version.

Regards.

**Comment by acca** [comment]
Just a backlink to track the progress: https://github.com/mmagnus/Pocket-Plus-Calibre-Plugin/issues/4

**Comment by mmagnus** [comment]
@acca @alvaroreig I think it might be fixed now https://github.com/mmagnus/Pocket-Plus-Calibre-Plugin/issues/4

**Comment by alvaroreig** [comment]
Thanks a lot @mmagnus ! Pocket2kindle is already updated to use the latest recipe.

**Comment by mmagnus** [comment]
Enjoy!
