### ISSUE TITLE
.env-sample file not found

### ISSUE THREAD

**Issue by mizzunet** [alvaroreig/pocket2kindle#5]
![Screenshot_20210525-190832](https://user-images.githubusercontent.com/10193999/119507735-b71af380-bd8c-11eb-9063-de0eed92e5e7.png)
https://raw.githubusercontent.com/alvaroreig/pocket2kindle/master/.env-sample
Mind to re upload?

**Comment by alvaroreig** [comment]
Hi @mizzunet 

You can find it here:

https://github.com/alvaroreig/pocket2kindle/commit/47ee8efeca2b53a4a8d3fb27bc6a185b74a496aa#diff-c4368a972a7fa60d9c4e333cebf68cdb9a67acb810451125c02e3b7eb2594e3d

I have to warn you, this software is broken and outdated. To make it work, you would have to update its recipe (that's simple) and check/refactor the nodejs code, which use outdated dependencies. I don't have time to maintain it right now, so I won't be able to assist you.

If I manage to get some time, I think the way to go would be to deprecate this repository and invest time in https://github.com/mmagnus/Pocket-Plus-Calibre-Plugin/discussions/39

Regards.
